#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T3.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="T3")]
	public partial class _Dat_CntxVistasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public _Dat_CntxVistasDataContext() : 
				base(global::T3.Properties.Settings.Default.T3ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public _Dat_CntxVistasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _Dat_CntxVistasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _Dat_CntxVistasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _Dat_CntxVistasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VST_CHEQUES_EMITIDOS> VST_CHEQUES_EMITIDOS
		{
			get
			{
				return this.GetTable<VST_CHEQUES_EMITIDOS>();
			}
		}
		
		public System.Data.Linq.Table<VST_REPOSICIONES_DET> VST_REPOSICIONES_DET
		{
			get
			{
				return this.GetTable<VST_REPOSICIONES_DET>();
			}
		}
		
		public System.Data.Linq.Table<VST_REPOS_ANTI_COUNT> VST_REPOS_ANTI_COUNT
		{
			get
			{
				return this.GetTable<VST_REPOS_ANTI_COUNT>();
			}
		}
		
		public System.Data.Linq.Table<VST_GRUPOIV> VST_GRUPOIV
		{
			get
			{
				return this.GetTable<VST_GRUPOIV>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_COB> VST_INC_COB
		{
			get
			{
				return this.GetTable<VST_INC_COB>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_VTAS> VST_INC_VTAS
		{
			get
			{
				return this.GetTable<VST_INC_VTAS>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_DISTRIBU> VST_INC_DISTRIBU
		{
			get
			{
				return this.GetTable<VST_INC_DISTRIBU>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_VARIOS> VST_INC_VARIOS
		{
			get
			{
				return this.GetTable<VST_INC_VARIOS>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_MARCF> VST_INC_MARCF
		{
			get
			{
				return this.GetTable<VST_INC_MARCF>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_MARCF_PRODUCTOS> VST_INC_MARCF_PRODUCTOS
		{
			get
			{
				return this.GetTable<VST_INC_MARCF_PRODUCTOS>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_MARCF_D> VST_INC_MARCF_D
		{
			get
			{
				return this.GetTable<VST_INC_MARCF_D>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_DISTRIBU_D> VST_INC_DISTRIBU_D
		{
			get
			{
				return this.GetTable<VST_INC_DISTRIBU_D>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_DISTRIBU_GTE> VST_INC_DISTRIBU_GTE
		{
			get
			{
				return this.GetTable<VST_INC_DISTRIBU_GTE>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_SI> VST_INC_SI
		{
			get
			{
				return this.GetTable<VST_INC_SI>();
			}
		}
		
		public System.Data.Linq.Table<VST_INC_SI_D> VST_INC_SI_D
		{
			get
			{
				return this.GetTable<VST_INC_SI_D>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_CHEQUES_EMITIDOS")]
	public partial class VST_CHEQUES_EMITIDOS
	{
		
		private string _cconcepto;
		
		private string _cbeneficiario;
		
		private System.Nullable<System.DateTime> _cfechaemision;
		
		private string _cname;
		
		private System.Nullable<int> _cnumcheqtransac;
		
		private string _cnumcuentad;
		
		private string _cbanco;
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidordpago;
		
		private int _cidemisioncheq;
		
		private System.Nullable<decimal> _cmontototal;
		
		private System.Nullable<byte> _cimpimiocheq;
		
		private System.Nullable<byte> _canulado;
		
		private string _cfpago;
		
		private System.Nullable<int> _cidcomprob;
		
		private string _cproveedor;
		
		private System.Nullable<int> _cidordpagodesc;
		
		private System.Nullable<byte> _antidescontado;
		
		private System.Nullable<decimal> _ctipotrospago;
		
		private System.Nullable<byte> _cotrospago;
		
		public VST_CHEQUES_EMITIDOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cconcepto", DbType="NVarChar(255)")]
		public string cconcepto
		{
			get
			{
				return this._cconcepto;
			}
			set
			{
				if ((this._cconcepto != value))
				{
					this._cconcepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbeneficiario", DbType="NVarChar(255)")]
		public string cbeneficiario
		{
			get
			{
				return this._cbeneficiario;
			}
			set
			{
				if ((this._cbeneficiario != value))
				{
					this._cbeneficiario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cfechaemision", DbType="DateTime")]
		public System.Nullable<System.DateTime> cfechaemision
		{
			get
			{
				return this._cfechaemision;
			}
			set
			{
				if ((this._cfechaemision != value))
				{
					this._cfechaemision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(100)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumcheqtransac", DbType="Int")]
		public System.Nullable<int> cnumcheqtransac
		{
			get
			{
				return this._cnumcheqtransac;
			}
			set
			{
				if ((this._cnumcheqtransac != value))
				{
					this._cnumcheqtransac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumcuentad", DbType="VarChar(30)")]
		public string cnumcuentad
		{
			get
			{
				return this._cnumcuentad;
			}
			set
			{
				if ((this._cnumcuentad != value))
				{
					this._cnumcuentad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cbanco", DbType="VarChar(10)")]
		public string cbanco
		{
			get
			{
				return this._cbanco;
			}
			set
			{
				if ((this._cbanco != value))
				{
					this._cbanco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidordpago", DbType="Int NOT NULL")]
		public int cidordpago
		{
			get
			{
				return this._cidordpago;
			}
			set
			{
				if ((this._cidordpago != value))
				{
					this._cidordpago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidemisioncheq", DbType="Int NOT NULL")]
		public int cidemisioncheq
		{
			get
			{
				return this._cidemisioncheq;
			}
			set
			{
				if ((this._cidemisioncheq != value))
				{
					this._cidemisioncheq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmontototal", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> cmontototal
		{
			get
			{
				return this._cmontototal;
			}
			set
			{
				if ((this._cmontototal != value))
				{
					this._cmontototal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cimpimiocheq", DbType="TinyInt")]
		public System.Nullable<byte> cimpimiocheq
		{
			get
			{
				return this._cimpimiocheq;
			}
			set
			{
				if ((this._cimpimiocheq != value))
				{
					this._cimpimiocheq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canulado", DbType="TinyInt")]
		public System.Nullable<byte> canulado
		{
			get
			{
				return this._canulado;
			}
			set
			{
				if ((this._canulado != value))
				{
					this._canulado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cfpago", DbType="VarChar(10)")]
		public string cfpago
		{
			get
			{
				return this._cfpago;
			}
			set
			{
				if ((this._cfpago != value))
				{
					this._cfpago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcomprob", DbType="Int")]
		public System.Nullable<int> cidcomprob
		{
			get
			{
				return this._cidcomprob;
			}
			set
			{
				if ((this._cidcomprob != value))
				{
					this._cidcomprob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidordpagodesc", DbType="Int")]
		public System.Nullable<int> cidordpagodesc
		{
			get
			{
				return this._cidordpagodesc;
			}
			set
			{
				if ((this._cidordpagodesc != value))
				{
					this._cidordpagodesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_antidescontado", DbType="TinyInt")]
		public System.Nullable<byte> antidescontado
		{
			get
			{
				return this._antidescontado;
			}
			set
			{
				if ((this._antidescontado != value))
				{
					this._antidescontado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctipotrospago", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ctipotrospago
		{
			get
			{
				return this._ctipotrospago;
			}
			set
			{
				if ((this._ctipotrospago != value))
				{
					this._ctipotrospago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cotrospago", DbType="TinyInt")]
		public System.Nullable<byte> cotrospago
		{
			get
			{
				return this._cotrospago;
			}
			set
			{
				if ((this._cotrospago != value))
				{
					this._cotrospago = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_REPOSICIONES_DET")]
	public partial class VST_REPOSICIONES_DET
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidreposiciones;
		
		private int _ciddreposiciones;
		
		private string _c_nomb_comer;
		
		private string _c_nomb_abreviado;
		
		private string _cnumdocu;
		
		private string _cnumdocuctrl;
		
		private string _cconcepto;
		
		private System.Nullable<decimal> _cmontototal;
		
		private string _ccuentaexep;
		
		private string _cname;
		
		private System.Nullable<System.DateTime> _cfechaemision;
		
		private string _ctipodocument;
		
		private System.Nullable<byte> _canticipogasto;
		
		private System.Nullable<decimal> _cmontosi;
		
		private System.Nullable<decimal> _cmontoexento;
		
		private System.Nullable<decimal> _cmontoimp;
		
		private System.Nullable<int> _cidordpagoanticipo;
		
		private byte _ctipodocumentodetalle;
		
		private string _cnumdocumafec;
		
		private string _cproveedor;
		
		public VST_REPOSICIONES_DET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidreposiciones", DbType="Int NOT NULL")]
		public int cidreposiciones
		{
			get
			{
				return this._cidreposiciones;
			}
			set
			{
				if ((this._cidreposiciones != value))
				{
					this._cidreposiciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciddreposiciones", DbType="Int NOT NULL")]
		public int ciddreposiciones
		{
			get
			{
				return this._ciddreposiciones;
			}
			set
			{
				if ((this._ciddreposiciones != value))
				{
					this._ciddreposiciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_nomb_comer", DbType="VarChar(255)")]
		public string c_nomb_comer
		{
			get
			{
				return this._c_nomb_comer;
			}
			set
			{
				if ((this._c_nomb_comer != value))
				{
					this._c_nomb_comer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_nomb_abreviado", DbType="VarChar(50)")]
		public string c_nomb_abreviado
		{
			get
			{
				return this._c_nomb_abreviado;
			}
			set
			{
				if ((this._c_nomb_abreviado != value))
				{
					this._c_nomb_abreviado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumdocu", DbType="VarChar(50)")]
		public string cnumdocu
		{
			get
			{
				return this._cnumdocu;
			}
			set
			{
				if ((this._cnumdocu != value))
				{
					this._cnumdocu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumdocuctrl", DbType="VarChar(20)")]
		public string cnumdocuctrl
		{
			get
			{
				return this._cnumdocuctrl;
			}
			set
			{
				if ((this._cnumdocuctrl != value))
				{
					this._cnumdocuctrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cconcepto", DbType="VarChar(100)")]
		public string cconcepto
		{
			get
			{
				return this._cconcepto;
			}
			set
			{
				if ((this._cconcepto != value))
				{
					this._cconcepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmontototal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cmontototal
		{
			get
			{
				return this._cmontototal;
			}
			set
			{
				if ((this._cmontototal != value))
				{
					this._cmontototal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccuentaexep", DbType="VarChar(50)")]
		public string ccuentaexep
		{
			get
			{
				return this._ccuentaexep;
			}
			set
			{
				if ((this._ccuentaexep != value))
				{
					this._ccuentaexep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(60)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cfechaemision", DbType="DateTime")]
		public System.Nullable<System.DateTime> cfechaemision
		{
			get
			{
				return this._cfechaemision;
			}
			set
			{
				if ((this._cfechaemision != value))
				{
					this._cfechaemision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctipodocument", DbType="VarChar(10)")]
		public string ctipodocument
		{
			get
			{
				return this._ctipodocument;
			}
			set
			{
				if ((this._ctipodocument != value))
				{
					this._ctipodocument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canticipogasto", DbType="TinyInt")]
		public System.Nullable<byte> canticipogasto
		{
			get
			{
				return this._canticipogasto;
			}
			set
			{
				if ((this._canticipogasto != value))
				{
					this._canticipogasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmontosi", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cmontosi
		{
			get
			{
				return this._cmontosi;
			}
			set
			{
				if ((this._cmontosi != value))
				{
					this._cmontosi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmontoexento", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cmontoexento
		{
			get
			{
				return this._cmontoexento;
			}
			set
			{
				if ((this._cmontoexento != value))
				{
					this._cmontoexento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmontoimp", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cmontoimp
		{
			get
			{
				return this._cmontoimp;
			}
			set
			{
				if ((this._cmontoimp != value))
				{
					this._cmontoimp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidordpagoanticipo", DbType="Int")]
		public System.Nullable<int> cidordpagoanticipo
		{
			get
			{
				return this._cidordpagoanticipo;
			}
			set
			{
				if ((this._cidordpagoanticipo != value))
				{
					this._cidordpagoanticipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctipodocumentodetalle", DbType="TinyInt")]
		public byte ctipodocumentodetalle
		{
			get
			{
				return this._ctipodocumentodetalle;
			}
			set
			{
				if ((this._ctipodocumentodetalle != value))
				{
					this._ctipodocumentodetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumdocumafec", DbType="VarChar(50)")]
		public string cnumdocumafec
		{
			get
			{
				return this._cnumdocumafec;
			}
			set
			{
				if ((this._cnumdocumafec != value))
				{
					this._cnumdocumafec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="VarChar(10)")]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_REPOS_ANTI_COUNT")]
	public partial class VST_REPOS_ANTI_COUNT
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidordpago;
		
		private string _ccount;
		
		private string _ctdocument;
		
		private string _cnumdocu;
		
		public VST_REPOS_ANTI_COUNT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidordpago", DbType="Int NOT NULL")]
		public int cidordpago
		{
			get
			{
				return this._cidordpago;
			}
			set
			{
				if ((this._cidordpago != value))
				{
					this._cidordpago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccount", DbType="NVarChar(20)")]
		public string ccount
		{
			get
			{
				return this._ccount;
			}
			set
			{
				if ((this._ccount != value))
				{
					this._ccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctdocument", DbType="NVarChar(10)")]
		public string ctdocument
		{
			get
			{
				return this._ctdocument;
			}
			set
			{
				if ((this._ctdocument != value))
				{
					this._ctdocument = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnumdocu", DbType="NVarChar(30)")]
		public string cnumdocu
		{
			get
			{
				return this._cnumdocu;
			}
			set
			{
				if ((this._cnumdocu != value))
				{
					this._cnumdocu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_GRUPOIV")]
	public partial class VST_GRUPOIV
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidgrupincentivar;
		
		private string _cidcargonom;
		
		private string _cgrupovta;
		
		private string _cdescargo;
		
		private string _cdesgrupo;
		
		private string _cdesgrupovta;
		
		public VST_GRUPOIV()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgrupovta", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cgrupovta
		{
			get
			{
				return this._cgrupovta;
			}
			set
			{
				if ((this._cgrupovta != value))
				{
					this._cgrupovta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescargo", DbType="VarChar(100)")]
		public string cdescargo
		{
			get
			{
				return this._cdescargo;
			}
			set
			{
				if ((this._cdescargo != value))
				{
					this._cdescargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesgrupo", DbType="VarChar(100)")]
		public string cdesgrupo
		{
			get
			{
				return this._cdesgrupo;
			}
			set
			{
				if ((this._cdesgrupo != value))
				{
					this._cdesgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesgrupovta", DbType="VarChar(50)")]
		public string cdesgrupovta
		{
			get
			{
				return this._cdesgrupovta;
			}
			set
			{
				if ((this._cdesgrupovta != value))
				{
					this._cdesgrupovta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_COB")]
	public partial class VST_INC_COB
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidgrupincentivar;
		
		private string _cdescripcion;
		
		private System.Nullable<byte> _civfijo;
		
		private string _cidcargonom;
		
		public VST_INC_COB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civfijo", DbType="TinyInt")]
		public System.Nullable<byte> civfijo
		{
			get
			{
				return this._civfijo;
			}
			set
			{
				if ((this._civfijo != value))
				{
					this._civfijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_VTAS")]
	public partial class VST_INC_VTAS
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidgrupincentivar;
		
		private string _cdescripcion;
		
		private System.Nullable<byte> _civfijo;
		
		private string _cidcargonom;
		
		public VST_INC_VTAS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civfijo", DbType="TinyInt")]
		public System.Nullable<byte> civfijo
		{
			get
			{
				return this._civfijo;
			}
			set
			{
				if ((this._civfijo != value))
				{
					this._civfijo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_DISTRIBU")]
	public partial class VST_INC_DISTRIBU
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincdistribu;
		
		private int _cidgrupincentivar;
		
		private string _cidcargonom;
		
		private string _cdescripcion;
		
		public VST_INC_DISTRIBU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincdistribu", DbType="Int NOT NULL")]
		public int cidincdistribu
		{
			get
			{
				return this._cidincdistribu;
			}
			set
			{
				if ((this._cidincdistribu != value))
				{
					this._cidincdistribu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_VARIOS")]
	public partial class VST_INC_VARIOS
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincvarios;
		
		private int _cidgrupincentivar;
		
		private string _cidcargonom;
		
		private string _cdescripcion;
		
		public VST_INC_VARIOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincvarios", DbType="Int NOT NULL")]
		public int cidincvarios
		{
			get
			{
				return this._cidincvarios;
			}
			set
			{
				if ((this._cidincvarios != value))
				{
					this._cidincvarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_MARCF")]
	public partial class VST_INC_MARCF
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincmarcafoco;
		
		private int _cidgrupincentivar;
		
		private string _cidcargonom;
		
		private string _cdescripcion;
		
		public VST_INC_MARCF()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincmarcafoco", DbType="Int NOT NULL")]
		public int cidincmarcafoco
		{
			get
			{
				return this._cidincmarcafoco;
			}
			set
			{
				if ((this._cidincmarcafoco != value))
				{
					this._cidincmarcafoco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_MARCF_PRODUCTOS")]
	public partial class VST_INC_MARCF_PRODUCTOS
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincmarcafoco;
		
		private decimal _cano;
		
		private decimal _cmes;
		
		private string _ccanal;
		
		private string _cestable;
		
		private System.Nullable<char> _ctodos;
		
		private string _cproveedor;
		
		private string _cgrupo;
		
		private string _csubgrupo;
		
		private System.Nullable<int> _cconjunto;
		
		private string _cproducto;
		
		public VST_INC_MARCF_PRODUCTOS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincmarcafoco", DbType="Int NOT NULL")]
		public int cidincmarcafoco
		{
			get
			{
				return this._cidincmarcafoco;
			}
			set
			{
				if ((this._cidincmarcafoco != value))
				{
					this._cidincmarcafoco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cano", DbType="Decimal(4,0) NOT NULL")]
		public decimal cano
		{
			get
			{
				return this._cano;
			}
			set
			{
				if ((this._cano != value))
				{
					this._cano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmes", DbType="Decimal(2,0) NOT NULL")]
		public decimal cmes
		{
			get
			{
				return this._cmes;
			}
			set
			{
				if ((this._cmes != value))
				{
					this._cmes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccanal", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccanal
		{
			get
			{
				return this._ccanal;
			}
			set
			{
				if ((this._ccanal != value))
				{
					this._ccanal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cestable", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cestable
		{
			get
			{
				return this._cestable;
			}
			set
			{
				if ((this._cestable != value))
				{
					this._cestable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctodos", DbType="VarChar(1)")]
		public System.Nullable<char> ctodos
		{
			get
			{
				return this._ctodos;
			}
			set
			{
				if ((this._ctodos != value))
				{
					this._ctodos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgrupo", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string cgrupo
		{
			get
			{
				return this._cgrupo;
			}
			set
			{
				if ((this._cgrupo != value))
				{
					this._cgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csubgrupo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string csubgrupo
		{
			get
			{
				return this._csubgrupo;
			}
			set
			{
				if ((this._csubgrupo != value))
				{
					this._csubgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cconjunto", DbType="Int")]
		public System.Nullable<int> cconjunto
		{
			get
			{
				return this._cconjunto;
			}
			set
			{
				if ((this._cconjunto != value))
				{
					this._cconjunto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproducto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string cproducto
		{
			get
			{
				return this._cproducto;
			}
			set
			{
				if ((this._cproducto != value))
				{
					this._cproducto = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_MARCF_D")]
	public partial class VST_INC_MARCF_D
	{
		
		private int _cidgrupincentivar;
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincmarcafoco;
		
		private int _cidincmarcafocod;
		
		private decimal _cano;
		
		private decimal _cmes;
		
		private string _ccanal;
		
		private string _cestable;
		
		private string _cproveedor;
		
		private string _cgrupo;
		
		private string _csubgrupo;
		
		private string _cproducto;
		
		private System.Nullable<char> _ctodos;
		
		private System.Nullable<decimal> _cporcactivamin;
		
		private string _cdescripcion;
		
		private string _cdesccanal;
		
		private string _cdesctestable;
		
		private string _cdesctelemento;
		
		private string _ccodelemento;
		
		public VST_INC_MARCF_D()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincmarcafoco", DbType="Int NOT NULL")]
		public int cidincmarcafoco
		{
			get
			{
				return this._cidincmarcafoco;
			}
			set
			{
				if ((this._cidincmarcafoco != value))
				{
					this._cidincmarcafoco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincmarcafocod", DbType="Int NOT NULL")]
		public int cidincmarcafocod
		{
			get
			{
				return this._cidincmarcafocod;
			}
			set
			{
				if ((this._cidincmarcafocod != value))
				{
					this._cidincmarcafocod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cano", DbType="Decimal(4,0) NOT NULL")]
		public decimal cano
		{
			get
			{
				return this._cano;
			}
			set
			{
				if ((this._cano != value))
				{
					this._cano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmes", DbType="Decimal(2,0) NOT NULL")]
		public decimal cmes
		{
			get
			{
				return this._cmes;
			}
			set
			{
				if ((this._cmes != value))
				{
					this._cmes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccanal", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccanal
		{
			get
			{
				return this._ccanal;
			}
			set
			{
				if ((this._ccanal != value))
				{
					this._ccanal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cestable", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cestable
		{
			get
			{
				return this._cestable;
			}
			set
			{
				if ((this._cestable != value))
				{
					this._cestable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="VarChar(5)")]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgrupo", DbType="VarChar(5)")]
		public string cgrupo
		{
			get
			{
				return this._cgrupo;
			}
			set
			{
				if ((this._cgrupo != value))
				{
					this._cgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_csubgrupo", DbType="VarChar(10)")]
		public string csubgrupo
		{
			get
			{
				return this._csubgrupo;
			}
			set
			{
				if ((this._csubgrupo != value))
				{
					this._csubgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproducto", DbType="VarChar(20)")]
		public string cproducto
		{
			get
			{
				return this._cproducto;
			}
			set
			{
				if ((this._cproducto != value))
				{
					this._cproducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctodos", DbType="VarChar(1)")]
		public System.Nullable<char> ctodos
		{
			get
			{
				return this._ctodos;
			}
			set
			{
				if ((this._ctodos != value))
				{
					this._ctodos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cporcactivamin", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cporcactivamin
		{
			get
			{
				return this._cporcactivamin;
			}
			set
			{
				if ((this._cporcactivamin != value))
				{
					this._cporcactivamin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(255)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesccanal", DbType="NVarChar(50)")]
		public string cdesccanal
		{
			get
			{
				return this._cdesccanal;
			}
			set
			{
				if ((this._cdesccanal != value))
				{
					this._cdesccanal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesctestable", DbType="NVarChar(50)")]
		public string cdesctestable
		{
			get
			{
				return this._cdesctestable;
			}
			set
			{
				if ((this._cdesctestable != value))
				{
					this._cdesctestable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesctelemento", DbType="VarChar(9)")]
		public string cdesctelemento
		{
			get
			{
				return this._cdesctelemento;
			}
			set
			{
				if ((this._cdesctelemento != value))
				{
					this._cdesctelemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccodelemento", DbType="VarChar(30)")]
		public string ccodelemento
		{
			get
			{
				return this._ccodelemento;
			}
			set
			{
				if ((this._ccodelemento != value))
				{
					this._ccodelemento = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_DISTRIBU_D")]
	public partial class VST_INC_DISTRIBU_D
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidgrupincentivar;
		
		private int _cidincdistribu;
		
		private int _cidincdistribud;
		
		private string _cproveedor;
		
		private string _cgrupo;
		
		private decimal _cano;
		
		private decimal _cmes;
		
		private string _ccomision;
		
		private string _cname;
		
		private string _c_nomb_abreviado;
		
		private System.Nullable<byte> _cvendedor;
		
		private System.Nullable<byte> _cgercomer;
		
		private System.Nullable<byte> _cgventas;
		
		private System.Nullable<byte> _cgerarea;
		
		public VST_INC_DISTRIBU_D()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Int NOT NULL")]
		public int cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincdistribu", DbType="Int NOT NULL")]
		public int cidincdistribu
		{
			get
			{
				return this._cidincdistribu;
			}
			set
			{
				if ((this._cidincdistribu != value))
				{
					this._cidincdistribu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincdistribud", DbType="Int NOT NULL")]
		public int cidincdistribud
		{
			get
			{
				return this._cidincdistribud;
			}
			set
			{
				if ((this._cidincdistribud != value))
				{
					this._cidincdistribud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgrupo", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string cgrupo
		{
			get
			{
				return this._cgrupo;
			}
			set
			{
				if ((this._cgrupo != value))
				{
					this._cgrupo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cano", DbType="Decimal(4,0) NOT NULL")]
		public decimal cano
		{
			get
			{
				return this._cano;
			}
			set
			{
				if ((this._cano != value))
				{
					this._cano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmes", DbType="Decimal(2,0) NOT NULL")]
		public decimal cmes
		{
			get
			{
				return this._cmes;
			}
			set
			{
				if ((this._cmes != value))
				{
					this._cmes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccomision", DbType="VarChar(30)")]
		public string ccomision
		{
			get
			{
				return this._ccomision;
			}
			set
			{
				if ((this._ccomision != value))
				{
					this._ccomision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="VarChar(100)")]
		public string cname
		{
			get
			{
				return this._cname;
			}
			set
			{
				if ((this._cname != value))
				{
					this._cname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_nomb_abreviado", DbType="VarChar(50)")]
		public string c_nomb_abreviado
		{
			get
			{
				return this._c_nomb_abreviado;
			}
			set
			{
				if ((this._c_nomb_abreviado != value))
				{
					this._c_nomb_abreviado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvendedor", DbType="TinyInt")]
		public System.Nullable<byte> cvendedor
		{
			get
			{
				return this._cvendedor;
			}
			set
			{
				if ((this._cvendedor != value))
				{
					this._cvendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgercomer", DbType="TinyInt")]
		public System.Nullable<byte> cgercomer
		{
			get
			{
				return this._cgercomer;
			}
			set
			{
				if ((this._cgercomer != value))
				{
					this._cgercomer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgventas", DbType="TinyInt")]
		public System.Nullable<byte> cgventas
		{
			get
			{
				return this._cgventas;
			}
			set
			{
				if ((this._cgventas != value))
				{
					this._cgventas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgerarea", DbType="TinyInt")]
		public System.Nullable<byte> cgerarea
		{
			get
			{
				return this._cgerarea;
			}
			set
			{
				if ((this._cgerarea != value))
				{
					this._cgerarea = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_DISTRIBU_GTE")]
	public partial class VST_INC_DISTRIBU_GTE
	{
		
		private int _cgroupcomp;
		
		private string _ccompany;
		
		private int _cidincdistribu;
		
		private System.Nullable<byte> _cvendedor;
		
		private System.Nullable<byte> _cgerarea;
		
		private System.Nullable<byte> _cgventas;
		
		private System.Nullable<byte> _cgercomer;
		
		public VST_INC_DISTRIBU_GTE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgroupcomp", DbType="Int NOT NULL")]
		public int cgroupcomp
		{
			get
			{
				return this._cgroupcomp;
			}
			set
			{
				if ((this._cgroupcomp != value))
				{
					this._cgroupcomp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincdistribu", DbType="Int NOT NULL")]
		public int cidincdistribu
		{
			get
			{
				return this._cidincdistribu;
			}
			set
			{
				if ((this._cidincdistribu != value))
				{
					this._cidincdistribu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvendedor", DbType="TinyInt")]
		public System.Nullable<byte> cvendedor
		{
			get
			{
				return this._cvendedor;
			}
			set
			{
				if ((this._cvendedor != value))
				{
					this._cvendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgerarea", DbType="TinyInt")]
		public System.Nullable<byte> cgerarea
		{
			get
			{
				return this._cgerarea;
			}
			set
			{
				if ((this._cgerarea != value))
				{
					this._cgerarea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgventas", DbType="TinyInt")]
		public System.Nullable<byte> cgventas
		{
			get
			{
				return this._cgventas;
			}
			set
			{
				if ((this._cgventas != value))
				{
					this._cgventas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cgercomer", DbType="TinyInt")]
		public System.Nullable<byte> cgercomer
		{
			get
			{
				return this._cgercomer;
			}
			set
			{
				if ((this._cgercomer != value))
				{
					this._cgercomer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_SI")]
	public partial class VST_INC_SI
	{
		
		private string _cidcargonom;
		
		private string _cdescripcion;
		
		private string _ccompany;
		
		private decimal _cidincsim;
		
		private decimal _cidgrupincentivar;
		
		public VST_INC_SI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidcargonom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cidcargonom
		{
			get
			{
				return this._cidcargonom;
			}
			set
			{
				if ((this._cidcargonom != value))
				{
					this._cidcargonom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(100)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincsim", DbType="Decimal(18,0) NOT NULL")]
		public decimal cidincsim
		{
			get
			{
				return this._cidincsim;
			}
			set
			{
				if ((this._cidincsim != value))
				{
					this._cidincsim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Decimal(18,0) NOT NULL")]
		public decimal cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VST_INC_SI_D")]
	public partial class VST_INC_SI_D
	{
		
		private decimal _cidincsid;
		
		private decimal _cidincsim;
		
		private decimal _cano;
		
		private byte _ccuarto;
		
		private string _ctestable;
		
		private string _cproducto;
		
		private string _ccanal;
		
		private string _cdescripcion;
		
		private decimal _cidgrupincentivar;
		
		private string _ccompany;
		
		private string _cproveedor;
		
		private string _cdesccanal;
		
		private string _cdesctestable;
		
		public VST_INC_SI_D()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincsid", DbType="Decimal(18,0) NOT NULL")]
		public decimal cidincsid
		{
			get
			{
				return this._cidincsid;
			}
			set
			{
				if ((this._cidincsid != value))
				{
					this._cidincsid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidincsim", DbType="Decimal(18,0) NOT NULL")]
		public decimal cidincsim
		{
			get
			{
				return this._cidincsim;
			}
			set
			{
				if ((this._cidincsim != value))
				{
					this._cidincsim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cano", DbType="Decimal(18,0) NOT NULL")]
		public decimal cano
		{
			get
			{
				return this._cano;
			}
			set
			{
				if ((this._cano != value))
				{
					this._cano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccuarto", DbType="TinyInt NOT NULL")]
		public byte ccuarto
		{
			get
			{
				return this._ccuarto;
			}
			set
			{
				if ((this._ccuarto != value))
				{
					this._ccuarto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctestable", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ctestable
		{
			get
			{
				return this._ctestable;
			}
			set
			{
				if ((this._ctestable != value))
				{
					this._ctestable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cproducto
		{
			get
			{
				return this._cproducto;
			}
			set
			{
				if ((this._cproducto != value))
				{
					this._cproducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccanal", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccanal
		{
			get
			{
				return this._ccanal;
			}
			set
			{
				if ((this._ccanal != value))
				{
					this._ccanal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdescripcion", DbType="VarChar(255)")]
		public string cdescripcion
		{
			get
			{
				return this._cdescripcion;
			}
			set
			{
				if ((this._cdescripcion != value))
				{
					this._cdescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidgrupincentivar", DbType="Decimal(18,0) NOT NULL")]
		public decimal cidgrupincentivar
		{
			get
			{
				return this._cidgrupincentivar;
			}
			set
			{
				if ((this._cidgrupincentivar != value))
				{
					this._cidgrupincentivar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccompany", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ccompany
		{
			get
			{
				return this._ccompany;
			}
			set
			{
				if ((this._ccompany != value))
				{
					this._ccompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cproveedor", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string cproveedor
		{
			get
			{
				return this._cproveedor;
			}
			set
			{
				if ((this._cproveedor != value))
				{
					this._cproveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesccanal", DbType="NVarChar(50)")]
		public string cdesccanal
		{
			get
			{
				return this._cdesccanal;
			}
			set
			{
				if ((this._cdesccanal != value))
				{
					this._cdesccanal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cdesctestable", DbType="NVarChar(50)")]
		public string cdesctestable
		{
			get
			{
				return this._cdesctestable;
			}
			set
			{
				if ((this._cdesctestable != value))
				{
					this._cdesctestable = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
