//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17379
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17379.
// 
#pragma warning disable 1591

namespace T3._Cls_EmailValidate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ser_EmailValidateSoap", Namespace="http://tempuri.org/")]
    public partial class Ser_EmailValidate : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _Mtd_ValidarEmailUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback _Mtd_BorrarEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ser_EmailValidate() {
            this.Url = global::T3.Properties.Settings.Default.T3__Slc_EmailValidate_Ser_EmailValidate;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _Mtd_ValidarEmailUserCompletedEventHandler _Mtd_ValidarEmailUserCompleted;
        
        /// <remarks/>
        public event _Mtd_BorrarEmailCompletedEventHandler _Mtd_BorrarEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_Mtd_ValidarEmailUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool _Mtd_ValidarEmailUser(string _P_Str_Email, string _P_Str_Compania, string _P_Str_Nombre) {
            object[] results = this.Invoke("_Mtd_ValidarEmailUser", new object[] {
                        _P_Str_Email,
                        _P_Str_Compania,
                        _P_Str_Nombre});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void _Mtd_ValidarEmailUserAsync(string _P_Str_Email, string _P_Str_Compania, string _P_Str_Nombre) {
            this._Mtd_ValidarEmailUserAsync(_P_Str_Email, _P_Str_Compania, _P_Str_Nombre, null);
        }
        
        /// <remarks/>
        public void _Mtd_ValidarEmailUserAsync(string _P_Str_Email, string _P_Str_Compania, string _P_Str_Nombre, object userState) {
            if ((this._Mtd_ValidarEmailUserOperationCompleted == null)) {
                this._Mtd_ValidarEmailUserOperationCompleted = new System.Threading.SendOrPostCallback(this.On_Mtd_ValidarEmailUserOperationCompleted);
            }
            this.InvokeAsync("_Mtd_ValidarEmailUser", new object[] {
                        _P_Str_Email,
                        _P_Str_Compania,
                        _P_Str_Nombre}, this._Mtd_ValidarEmailUserOperationCompleted, userState);
        }
        
        private void On_Mtd_ValidarEmailUserOperationCompleted(object arg) {
            if ((this._Mtd_ValidarEmailUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._Mtd_ValidarEmailUserCompleted(this, new _Mtd_ValidarEmailUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/_Mtd_BorrarEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool _Mtd_BorrarEmail(string _Str_Email) {
            object[] results = this.Invoke("_Mtd_BorrarEmail", new object[] {
                        _Str_Email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void _Mtd_BorrarEmailAsync(string _Str_Email) {
            this._Mtd_BorrarEmailAsync(_Str_Email, null);
        }
        
        /// <remarks/>
        public void _Mtd_BorrarEmailAsync(string _Str_Email, object userState) {
            if ((this._Mtd_BorrarEmailOperationCompleted == null)) {
                this._Mtd_BorrarEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.On_Mtd_BorrarEmailOperationCompleted);
            }
            this.InvokeAsync("_Mtd_BorrarEmail", new object[] {
                        _Str_Email}, this._Mtd_BorrarEmailOperationCompleted, userState);
        }
        
        private void On_Mtd_BorrarEmailOperationCompleted(object arg) {
            if ((this._Mtd_BorrarEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._Mtd_BorrarEmailCompleted(this, new _Mtd_BorrarEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void _Mtd_ValidarEmailUserCompletedEventHandler(object sender, _Mtd_ValidarEmailUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _Mtd_ValidarEmailUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _Mtd_ValidarEmailUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void _Mtd_BorrarEmailCompletedEventHandler(object sender, _Mtd_BorrarEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _Mtd_BorrarEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _Mtd_BorrarEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591